{
  "openapi": "3.0.0",
  "info": {
    "title": "OAuth (Partner)",
    "version": "1.0",
    "contact": {
      "name": "Cuscal"
    },
    "description": "Defines the OAuth endponts exposed to support CDR. Note in this first API iteration this endpoint does not implement its required end state\n"
  },
  "servers": [
    {
      "url": "https://internalapi.dev.cds.cuscal.com.au/auth/v1",
      "description": "Dev"
    },
    {
      "url": "https://cds.cuscal.com.au/auth/v1",
      "description": "Production"
    }
  ],
  "paths": {
    "/oauth20/token": {
      "post": {
        "summary": "POST Token",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "access_token": {
                      "type": "string"
                    },
                    "token_type": {
                      "type": "string"
                    },
                    "scope": {
                      "type": "string",
                      "description": "The scope(s) that are bound to the token"
                    },
                    "expires_in": {
                      "type": "string",
                      "description": "Length of time in seconds the token is valid"
                    }
                  }
                },
                "examples": {
                  "OB-bearer token": {
                    "value": {
                      "access_token": "FNtns35O1vhDSTjcGPpX",
                      "scope": "openid, profile",
                      "token_type": "bearer",
                      "expires_in": 3599
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Endpoint to retrieve security tokens.  \n\nTwo Grant Types are suppported \n1. Client Credentials\n2. Authorization Code \n3. Refresh token\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "grant_type": {
                    "type": "string",
                    "enum": [
                      "client_credentials",
                      "authorization_code",
                      "refresh_token"
                    ],
                    "example": "client_credentials"
                  },
                  "client_secret": {
                    "type": "string",
                    "example": "3oA3GUySBQbdLINHjXiV"
                  },
                  "scopes": {
                    "type": "string",
                    "example": "openid"
                  },
                  "client_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "grant_type"
                ]
              },
              "examples": {
                "MerchantWarrior(EDAF)": {
                  "value": {
                    "grant_type": "client_credentials",
                    "scopes": "openid",
                    "client_id": "mwa-acqpayment-01",
                    "client_secret": "nUk4d6259jC6MhA3dLgc"
                  }
                },
                "Introspect Client": {
                  "value": {
                    "grant_type": "client_credentials",
                    "scopes": "openid",
                    "client_id": "JTguz57TgbTFfS8y808O",
                    "client_secret": "bEdVbva4m00yRKg0ZhsI"
                  }
                },
                "OB-ClientCredentials": {
                  "value": {
                    "grant_type": "client_credentials",
                    "client_id": "cuscal-openbanking-client01",
                    "client_secret": "3oA3GUySBQbdllNHjXiV",
                    "scope": "openid profile"
                  }
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {
                  "grant_type": {
                    "type": "string",
                    "example": "client_credentials"
                  },
                  "client_id": {
                    "type": "string"
                  },
                  "client_secret": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "example-xml": {
                  "value": {
                    "grant_type": "client_credentials",
                    "client_id": "cuscal-openbanking-client01",
                    "client_secret": "3oA3GUySBQbdllNHjXiV"
                  }
                }
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": ""
        },
        "operationId": "POST-token"
      },
      "parameters": []
    }
  },
  "components": {
    "securitySchemes": {}
  }
}